# Logging Configuration
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%X{exchangeId}] [%X{customField}] %c{2.} - %s%e%n

# Camel Configuration
camel.main.name=MDCDemo
camel.main.useMDCLogging=true
